/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo1 */

#ifndef _Included_demo1
#define _Included_demo1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo1
 * Method:    accessStaticMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_demo1_accessStaticMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
