/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
/* Header for class HelloNative */

//#ifndef _Included_HelloNative
//#define _Included_HelloNative
//#ifdef __cplusplus
//extern "C" {
//#endif
///*
// * Class:     HelloNative
// * Method:    printHello
// * Signature: ()V
// */
//JNIEXPORT void JNICALL Java_HelloNative_printHello
//  (JNIEnv *, jobject);
//
//#ifdef __cplusplus
//}
//#endif
//#endif
//gcc -I/home/zw/user/java/jdk1.7.0_80/include -I/home/zw/user/java/jdk1.7.0_80/include/linux  -fPIC -shared -o jni.so org_jni_TestJni.c
