/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Cthread_Cthread */

#ifndef _Included_jni_Cthread_Cthread
#define _Included_jni_Cthread_Cthread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Cthread_Cthread
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_Cthread_Cthread_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
