/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJni */

#ifndef _Included_TestJni
#define _Included_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJni
 * Method:    yyy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestJni_yyy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
